on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LinuxRocks2000/sitix-rewrite
          ref: master
          path: sitix-rewrite
      - uses: actions/checkout@v2
        with:
          path: sitix-ghp-test
      - name: Build website
        run: |
             cd sitix-ghp-test
             ../sitix-rewrite/bin/sitix-ubuntu site -o gh-pages
             git config --global user.name Robot
             git config --global user.email notan@emailaddr.ess
             git add .
             git commit -am "automated build"
             git push
