on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LinuxRocks2000/sitix-rewrite
          ref: master
          path: sitix-rewrite
      - uses: actions/checkout@v2
      - name: Sitix build
        run: |
             echo "hi"
             ls -la
