on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LinuxRocks2000/sitix-rewrite
          ref: master
          path: sitix-rewrite
      - uses: actions/checkout@v2
        with:
          path: sitix-ghp-test
      - uses: actions/cmake-action@v1.3.0
        with:
          source-dir: sitix-rewrite
      - name: Sitix build
        run: |
          ls -la sitix-rewrite
          ls -la sitix-rewrite/build
