on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sitix build
        run: |
             git clone git@github.com:LinuxRocks2000/sitix-rewrite.git
             cd sitix-rewrite
             mkdir build
             cd build
             cmake ..
             cmake --build .
